name: firebasetest
description: "firebase"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.2.0
  firebase_database: 11.0.3


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: true
  image_path: "icons/app_icon.png"

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true